"""Remove users

Revision ID: 2d3e8e45071f
Revises: be24780c0da0
Create Date: 2025-11-08 14:27:08.247229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3e8e45071f'
down_revision = 'be24780c0da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_token_refresh_token'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_table('user_account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('email', sa.VARCHAR(length=256), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('create_time', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('update_time', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=1)
    op.create_table('refresh_token',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(length=512), nullable=False),
    sa.Column('used', sa.BOOLEAN(), nullable=False),
    sa.Column('exp', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('create_time', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('update_time', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_refresh_token'), 'refresh_token', ['refresh_token'], unique=1)
    # ### end Alembic commands ###
